version: 2
updates:
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    groups:
      docs-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
